### ISSUE TITLE
KeyError: 'No such transport: rabbitmq.  Did you mean librabbitmq?'

### ISSUE THREAD

**Issue by samgclarke** [dokku/dokku-rabbitmq#6]
Getting this when trying to use Dokku + DigitalOcean + Celery.

I changed environment variable BROKER_BACKEND to "librabbitmq", but still no change.

**Comment by josegonzalez** [comment]
A couple of things:

- This is almost certainly an application error, not related to dokku-rabbitmq.
- How are you configuring celery? What version of celery are you running? Can you show us the full stacktrace for both configuration values of BROKER_BACKEND?

**Comment by samgclarke** [comment]
Here is the Stacktrace:

    [2015-09-16 00:58:38 +0000] [182] [INFO] Starting gunicorn 19.3.0
    [2015-09-16 00:58:38 +0000] [182] [INFO] Listening at: http://0.0.0.0:5000 (182)
    [2015-09-16 00:58:38 +0000] [182] [INFO] Using worker: sync
    [2015-09-16 00:58:38 +0000] [187] [INFO] Booting worker with pid: 187
    [2015-09-16 00:58:57 +0000] [187] [ERROR] Error handling request
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
        self.handle_request(listener, req, client, addr)
      File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/app/.heroku/python/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
        return cors_after_request(app.make_response(f(*args, **kwargs)))
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/app/.heroku/python/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
        return cors_after_request(app.make_response(f(*args, **kwargs)))
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/app/.heroku/python/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
        return func(*args, **kwargs)
      File "/app/scriptspeaker/decorators.py", line 14, in decorated_function
        return func(*args, **kwargs)
      File "/app/scriptspeaker/views.py", line 360, in render_script
        OUTPUT_PATH=OUTPUT_PATH
      File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
        return self.apply_async(args, kwargs)
      File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
        **dict(self._get_exec_options(), **options)
      File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 347, in send_task
        with self.producer_or_acquire(producer) as P:
      File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 402, in producer_or_acquire
        producer, self.amqp.producer_pool.acquire, block=True,
      File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/amqp.py", line 492, in producer_pool
        self.app.pool,
      File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 608, in pool
        self._pool = self.connection().Pool(limit=limit)
      File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 385, in connection
        'BROKER_CONNECTION_TIMEOUT', connect_timeout
      File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 165, in __init__
        if not get_transport_cls(transport).can_parse_url:
      File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/__init__.py", line 109, in get_transport_cls
        _transport_cache[transport] = resolve_transport(transport)
      File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/__init__.py", line 88, in resolve_transport
        transport, alt))
    KeyError: 'No such transport: rabbitmq.  Did you mean librabbitmq?'

**Comment by josegonzalez** [comment]
Do you have a sample app that I can use to replicate this issue?

**Comment by josegonzalez** [comment]
Bump :)
