### ISSUE TITLE
can't connect to exposed DSN

### ISSUE THREAD

**Issue by cocodrino** [dokku/dokku-rabbitmq#64]
hi, hope you're fine, I expose my rabbitmq service because I need connect an app running in the same server but not with dokku, rabbitmq:info returns me something like this

```
 Dsn:                 amqp://rabbitmq:c109xxxa570f20963cb39241f@dokku-rabbitmq-rabbitmq:5672/rabbitmq
 Exposed ports:       5672->14265 4369->396 35197->8846 15672->11881 
```

I've tried to connect my local app with this DSN
 amqp://rabbitmq:c109xxxa570f20963cb39241f@dokku-rabbitmq-rabbitmq:5672/rabbitmq

and this (because I'm not sure if 5672 is the exposed port or it's 14265)
 amqp://rabbitmq:c109xxxa570f20963cb39241f@dokku-rabbitmq-rabbitmq:14265/rabbitmq

in both cases I get this

```

 ERROR RPC CLIENT { Error: getaddrinfo EAI_AGAIN dokku-rabbitmq-rabbitmq dokku-rabbitmq-rabbitmq:14265
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  cause:
   { Error: getaddrinfo EAI_AGAIN dokku-rabbitmq-rabbitmq dokku-rabbitmq-rabbitmq:14265
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'dokku-rabbitmq-rabbitmq',
     host: 'dokku-rabbitmq-rabbitmq',
     port: 14265 },
  isOperational: true,
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dokku-rabbitmq-rabbitmq',
  host: 'dokku-rabbitmq-rabbitmq',
  port: 14265 }


```

Do I need change this DSN to connect me from outside from dokku? thank you so much, best regards

**Comment by cocodrino** [comment]
I replace dokku-rabbitmq-rabbitmq for my local ip

```
amqp://rabbitmq:c10997d49xxxxb39241f@127.0.0.1:14265/rabbitmq
```
